# Generated by Django 2.2.6 on 2019-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('shoulders', 'Shoulders'), ('chest', 'Chest'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('ABS', 'ABS'), ('legs', 'Legs'), ('back', 'Back')], max_length=64),
        ),
    ]
