# Generated by Django 2.2.6 on 2019-10-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_profile_name'),
        ('exercises', '0006_exercise_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating value, integer from 1 to 5')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='exercises.Exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='userprofile.Profile')),
            ],
            options={
                'unique_together': {('exercise', 'owner')},
            },
        ),
    ]
